### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by virath** [forcedotcom/SalesforceMobileSDK-iOS-Package#106]
Using cordova CLI version 4.1.2 to create the hybrid app.
/Volumes/Macintosh HD2/SDK3/HybridApps/myAPP /Volumes/Macintosh HD2/SDK3
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
/Volumes/Macintosh HD2/SDK3

Can you check this and let me know what exactly need to be done?

**Comment by khawkins** [comment]
This should be fixed in our next patch release of the npm package.  In the meantime, the workaround is to use paths without spaces in them.
