### ISSUE TITLE
Issue creating new hybrid_remote app

### ISSUE THREAD

**Issue by securitybites** [forcedotcom/SalesforceMobileSDK-iOS-Package#137]
While following the Mobile SDK trailhead documentation and running `forceios create`, the following error is generated:

```
forceios failed

Command failed: cordova platform add ios@4.4.0
Error: cordovaProject.projectConfig.getFileResources is not a function
```

I believe ios 4.4.0 does not support `.getFileResources` like 4.3.0 did.

**Comment by wmathurin** [comment]
We are not seeing the issue.
Could you run `cordova -v` and let us know what it returns?

**Comment by wmathurin** [comment]
Also what version of XCode are you using?

**Comment by securitybites** [comment]
Updating to Cordova v7.0.0 fixed the issue.
